### ISSUE TITLE
Issue: Public to private

### ISSUE THREAD

**Issue by openengg1** [acrlakshman/profileio#8]
The user's repository is public. This makes the data and the entire profile susceptible to data theft.  Is there a workaround for this?

**Comment by acrlakshman** [comment]
Since one of the goals of this repository/project is to generate and display user' profile in a rendered web page and resume and display it on github pages via depending on github actions, it is easy when this repository is made public. But if you are concerned about sharing the details in the repository to public, feel free to make your repository private from settings (**_settings -> change repository visibility_**). Please note that, once you make the repository private, you will not be able to use few features, such as github pages, build on netlify and vercel. Github will also put limit on github actions for autogeneration of webpages and resume. However once you make the repository private, you can feel free to generate the website and resume using the scripts provided in this repository directly on your local machine and push manually to your web server.

**Comment by openengg1** [comment]
Thanks Laksman!
